### ISSUE TITLE
Linux compilation instructions: minor fix needed

### ISSUE THREAD

**Issue by polycrates** [perseids-tools/morpheus#5]
I just compiled this on Fedora 37 - still works! 
Because of 'multiple definition' errors I had to add a cflag, so:
CFLAGS='-std=gnu89 -fcommon' make
Thanks for keeping this remarkable tool alive.

**Comment by zfletch** [comment]
Thank you! It looks like there was a change in GCC v10 that caused this issue (see https://wiki.gentoo.org/wiki/Project:Toolchain/Gcc_10_porting_notes/fno_common).

I've updated the README in the linked PR and I'll update the Dockerfile and upload a new version to Docker Hub next.
