### ISSUE TITLE
Missing dependencies in Ubuntu 22.04

### ISSUE THREAD

**Issue by nitardus** [perseids-tools/morpheus#7]
Today I had some trouble compiling the program, until it turned out that libfl-dev was missing on my system. Perhaps you could add this library also to the dependencies in the README file? Many thanks!

**Comment by zfletch** [comment]
Interesting, I tested it on an Ubuntu Docker container but not an actual instance of Ubuntu and there could be some differences. Did you install `flex` before trying to compile it?

**Comment by nitardus** [comment]
Yes, flex was installed beforehand. I've just tried the same again in my office on Linux Mint 21. Before installing libfl-dev, 
gcc gave me the following error:

gcc   setquant.o -lfl  -o setquant
/usr/bin/ld: -lfl kann nicht gefunden werden: Datei oder Verzeichnis nicht gefunden
collect2: error: ld returned 1 exit status
make[1]: *** [<eingebaut>: setquant] Fehler 1
rm setquant.o setquant.c
make[1]: Verzeichnis „.../morpheus-perseids/src/gkdict“ wird verlassen
make: *** [makefile:5: all] Fehler 2

(sorry for the German output: "-lfl kann nicht gefunden werden" is "cannot find -lfl", "Fehler" is "error")

Installing libfl-dev solved this problem.

**Comment by zfletch** [comment]
Do you remember how you installed flex? I tried on a fresh install of Ubuntu and after running `apt-get install flex`, I have the `libfl-dev` package:

```
$ dpkg -l | grep libfl-dev
ii  libfl-dev:amd64           2.6.4-8build2                           amd64        static library for flex (a fast lexical analyzer generator)
```
