### ISSUE TITLE
Morpheus database

### ISSUE THREAD

**Issue by carvalhar** [perseids-tools/morpheus#8]
Hi there,

I'm new to Perseids environment, but I'd like to know how is Morpheus database done. I couldn't understand neither find the correlation between Greek words and it's morphology, only the tables with Morpho stems as "aor inf".

My work experience is with PHP/MySQL and I was wondering if I could implement a database in another model, but I would need this morphology sources made by Perseids. 

I found the API, but I'm not sure if it's complete. 

Did anyone tried before a conversion to SQL database? I'd like to text a sintax tree, but user friendly.

Thank you in advance.

Sincerely,
Carlos

**Comment by zfletch** [comment]
This is a great question and I appreciate your interest in Morpheus. Unfortunately, the system is largely not documented. The only real existing documentation is a short paper from 1991 (https://doi.org/10.1093/llc/6.4.243). I can't share the whole thing due to copyright reasons, but this diagram shows how the system works at a high level.

<img width="529" alt="diagram" src="https://github.com/perseids-tools/morpheus/assets/3039310/47890ba1-ade1-4f7e-bfc3-d6724c1b073e">

Everything is driven from the stemlibs (https://github.com/perseids-tools/morpheus/tree/master/stemlib/Greek) which are written in Beta Code (https://en.wikipedia.org/wiki/Beta_Code). If you are interested in helping, learning how Morpheus works then writing documentation would be a great contribution to this project.

As far as I know, there are no efforts to convert this to SQL. You may also be interested in collaborating with https://github.com/cltk/ if you are working on a new or improved morphology engine.

**Comment by carvalhar** [comment]
Dear Zachary,

Thank you for your response. I downloaded the article using Sci-Hub.

I'd like to test a conversion to SQL tables (eg. MySQL), possibiliting the
use with PHP or other web programming language.
Therefore I would need to create this database from Morpheus data, but I
can't find it and I get lost in many files in these github projects.

I found a large XML file with these morph relations:
https://github.com/gcelano/LemmatizedAncientGreekXML/blob/master/Morpheus/MorpheusUnicode.xml.zip

So far it's the most similar to a morphological database that I could find.
It has this structure:
  <t>
    <i>77893</i>* --- entry id*
    <f>ἄνθρωπος</f>  *--- inflected word with diacritics *
    <b>ανθρωπος</b>   * --- inflected word without diacritics *
    <l>ἄνθρωπος</l> *-- lema with diacritics *
    <e>ανθρωπος</e>  * -- lema  without    diacritics *
    <p>n-s---mn-</p>* -- morphological data*
    <d>2895</d>* -- LSJ entry index (relating to what?)*
    <s>manfaced</s> *-- the first dict word translation? (it's not in LSJ
entry)*
    <a/>
  </t>

The first tag of this file is very explicative, and I know that "n-s---mn"
means "noun sg masc nom", but I couldn't find a table relating these terms.
Also, I have no idea how complete this XML is.

The same problem happens with Morphology Service API from Perseids:
https://sites.tufts.edu/perseusupdates/2012/11/01/morphology-service-beta/

This Api provides this more human readable structure:
https://services.perseids.org/bsp/morphologyservice/analysis/word?lang=grc&engine=morpheusgrc&word=%E1%BC%84%CE%BD%CE%B8%CF%81%CF%8E%CF%80%CE%BF%CF%82

<entry uri="">
<dict>
<hdwd xml:lang="grc">ἄνθρωπος</hdwd>
<pofs order="3">noun</pofs>
<decl>2nd</decl>
<gend>masculine</gend>
</dict>
<infl>
<term xml:lang="grc">
<stem>ἀνθρωπ</stem>
<suff>ος</suff>
</term>
<pofs order="3">noun</pofs>
<decl>2nd</decl>
<case order="7">nominative</case>
<gend>masculine</gend>
<num>singular</num>
<stemtype>os_ou</stemtype>
</infl>
</entry>

But once again I have no idea if this API has all the database or if it
lacks a lot of words and inflections. Also, I don't know how to obtain ALL
of these possible xmls from the API (ie., all indexed flexioned words),
because I don't have a complete list of these indexed words (the first XML
could be a source, but I don't know if it is complete).

At Github I have found tons of projects, many of them look like they are
abandoned and some others are using files from 27 years ago.

As far as I'm understanding, there is one big old file (made with C/C++
file databases?). That is, there is one source of this morphological data,
but it's quite old and many others were revised (some of them with
identifiables as "manually edited" or "bug #x"), but I can't discover which
one is the best and most complete to collect data for SQL format. My
impression is that many people worked with this raw data, with a lot of
different programming skills, and many projects have died without a full
release and documentation. But they are all indexed in github with similar
names and I'm definitely lost.

Any thoughts are welcome!

Best regards,
Carlos

Em qui., 24 de ago. de 2023 às 10:41, Zachary Fletcher <
***@***.***> escreveu:

**Comment by zfletch** [comment]
Apologies if I'm misunderstanding, but it sounds like you're trying to build a SQL database of all the word forms for which Morpheus returns a result. For example, you might have two rows that looks like this (simplified):

| word | stem | part of speech |
| - | - | - |
| καλῶν | καλέω | part sg pres act masc nom |
| καλῶν | καλός | adj pl neut gen |

Then a web application could easily look up some word's morphology with `SELECT * FROM morpheus WHERE word = 'καλῶν';`.

This may be difficult because Morpheus works differently from a relational database. When you ask it about καλῶν, it first tries to separate the stem from the ending and then checks both of them separately in its collection of stems and endings. The stems and endings are in the /stemlib/Greek directory I linked above. Morpheus also has some special case logic to deal with elision, crasis, dialectical differences (e.g. συν- vs. ξυν-), etc. If you'd like to figure out the logic, /src/anal/checkstring.c is a good place to start.

It may be possible to build this kind of morphological SQL database (and it would be an excellent resource for the community!) by finding all stems and endings in /stemlib/Greek, reverse engineering the special cases, and then creating every possible word. However, this may be a difficult engineering problem.

**Comment by carvalhar** [comment]
Yes, that's the problem. At first I thought that there was a database listing all possibilities by inflected word (as the XML from the first email provides), but Morpheus doesn't store data, and processes the word each time. But, as someone already did, both with the API and the big XML file, all this info can be exported and a relational SQL database can be built. 

A problem is that I have no idea of how many words Morpheus has, I mean, I didn't find the total amount of inflected words. Despite this, some words aren't found in the online Perseus dictionary, as far as I know, because it was not catalogued with the original texts indexed, but I'm not sure how it was done almost 30 years ago. However, Wiktionary has inflected words (manually added?) that could be a source to "steal" new words. I think it would be easier to store all these word possibilities into a relational database, acting like a cache from Morpheus' logic, than a time consuming process of calculus. 

The big problem is how to do this and be sure that it reached all Morpheus' possibilities.

**Comment by carvalhar** [comment]
This is more or less what I'm thinking of the sql database (because it needs to be more than just english)

table words
index  | inflected_word 
00001 | καλῶν 

table lema (maybe break even futher in dictionaries' tables)
index | lema | definition_LSJ  | definition_Bailly
00001 | καλέω | to call...  | appel...
00002 | καλός | beautiful... | beau...

Table lematized inflected words
index | word_index | lema_index 
00001  |  00001  | 00001  
00002  |  00001  | 00002 

Table properties
index | property
00001 | adj 
00002 | pl
00003 | part 

Table: lematized inflected words with properties 
index |  index_word | index_lema | index_property
00001 | 00001  | 00001  | 00001  
00001 | 00001  | 00001  | 00002
00001 | 00001  | 00002  | 00003
00001 | 00001  | 00002  | 00004

**Comment by carvalhar** [comment]
This is more or less what I'm thinking of the sql database (because it needs to be more than just english)

table words
index  | inflected_word 
00001 | καλῶν 

table lema 
index | lema
00001 | καλέω
00002 | καλός

table dicitionaries
index | dict
00001 | LSJ
00002 | Bailly 

table dict definitions (maybe separeted tables for each one?)
index | index_lema | index_dict | definition
00001 | 00001        |  00001   | to call...  
00002 | 00001        |  00002   | appel...  
00003 | 00002        |  00001   | beautiful...  
00004 | 00002        |  00002   | beau...  

Table lematized inflected words
index | word_index | lema_index 
00001  |  00001  | 00001  
00002  |  00001  | 00002 

Table properties (maybe even more divided, eg, by word class or property's type)
index | property
00001 | adj 
00002 | pl
00003 | part 
00004 | dialect_attic
00005 | crasis
00006 | epic

Table: lematized inflected words with properties 
index |  index_word | index_lema | index_property
00001 | 00001  | 00001  | 00001  
00002 | 00001  | 00001  | 00002
00003 | 00001  | 00002  | 00045
00004 | 00001  | 00002  | 00064

**Comment by zfletch** [comment]
I'm not sure how feasible it would be to extract all of Morpheus' possible generated morphologies. However, if you're looking for sources of morphological data, you may find ancient Greek XML treebanks useful. We have a collection [here](https://github.com/perseids-publications) and there's another project called the [AGLDT](https://perseusdl.github.io/treebank_data/) which includes a collection of treebanks.

If you take a look at an example treebank [XML](https://github.com/perseids-publications/gorman-trees/blob/master/public/xml/aeschines-1-1-50-bu1.xml) file, you can see lines that look like this:

```xml
<word id="5" form="πολλὰ" lemma="πολύς" postag="a-p---na-" relation="OBJ" head="9"/>
```

The important attributes for what you're working on are `form`, `lemma`, and `postag`. This line says that the word `πολλὰ` in this particular sentence is a form of `πολύς` and it is a neuter, plural, accusative adjective. (See [here](https://github.com/cltk/greek_treebank_perseus#readme) for information about how to read the `postag`.) These treebanks are all generated by hand, so they may have occasional errors, but the data should be pretty high quality.

Wiktionary is a great source and I worked on a similar project using Wiktionary data for verb conjugations. You can see it [here](https://apps.perseids.org/greek-conjugator/%CE%BB%CF%8D%CF%89). The script that crawled Wiktionary and extracted that data is [here](https://github.com/perseids-project/greek-conjugator-js/tree/master/scripts). Please feel free to reuse or modify it.

**Comment by zfletch** [comment]
> But, as someone already did, both with the API and the big XML file, all this info can be exported and a relational SQL database can be built. 

You might get a better answer asking in that repository, but I assume that [MorpheusUnicode.xml.zip](https://github.com/gcelano/LemmatizedAncientGreekXML/blob/master/Morpheus/MorpheusUnicode.xml.zip) is essentially a cache of Morpheus' results when run on all the words in the set of texts that are in that repository.

**Comment by carvalhar** [comment]
Thank you for your comments. I'll give it a try.
